### ISSUE TITLE
Add hash calculation

### ISSUE THREAD

**Issue by SPPearce** [nvnieuwk/nft-bam#1]
This looks great and I can't wait to simplify some of the nf-core modules with it.

It would be really nice if we could have a single function to calculate the md5sum of the reads directly, so we know that the content of the s/b/cram file is identical, even if the header changes.
A similar calculation on the header would make sense too, although I don't know if that is variable on conda or not; potentially the md5sum could calculate on both parts in a manner that isn't different between docker and conda.

**Comment by nvnieuwk** [comment]
Thank you for the suggestion! That seems like a good feature for the plugin to have

**Comment by nvnieuwk** [comment]
For future reference to myself: https://stackoverflow.com/questions/415953/how-can-i-generate-an-md5-hash-in-java
