### ISSUE TITLE
Plugin'nft-bam' found, but version 0.5.0 not found.

### ISSUE THREAD

**Issue by gloubsi** [nvnieuwk/nft-bam#18]
Hello,

First of all, thank you for quickly adding duplicateReadCount to getStatistics() method with the release nftbam version 0.5.0. On my side, we would like to use the latest version to benefit from the new feature. 

However, I have an error when specifying the plugin version 0.5.0 for nftbam to nf-test. I tried the command line option --plugin nftbam@0.5.0 and the plugin section in config file and both method arises an error (version not found).

When not specifying the version we would like to use in command line, nf-test says that the latest version of nftbam is not yet supported.

This is strange because on nf-test website, section plugin, we can see that the version newest version is 0.5.0. (https://plugins.nf-test.com/)

Do you have a workaround to solve this issue ?

Thank you very much for your time.

Best regards.

PS: For more details, see images attached.

![Capture d'écran 2024-11-05 151313](https://github.com/user-attachments/assets/5d7ea184-a12d-4963-9d7a-54f4d4d3a8dd)
![Capture d'écran 2024-11-05 151303](https://github.com/user-attachments/assets/a52ba27a-90c6-4c6b-9640-05ad5fee73a4)

**Comment by nvnieuwk** [comment]
Hi can you try to remove the nf-test plugins directory inside of the directory where you are running the tests? `rm -rf .nf-test/plugins`?

Also pinging @lukfor here, I think this is one of those cases where the plugins aren't getting downloaded correctly

**Comment by gloubsi** [comment]
To give more insight about our architecture, we create a docker image with nf-test alongside with others things and then execute nf-test command inside a docker container. We have recreated the image with the newer version of nf-test (to possibly reinstalled the new plugin) as a try to make it works. But it didn't.

I have deleted the .nf-test folder and it works great. Thank you very much. 

It's because we had the older 0.4.0 version of nft-bam inside .nf-test folder stored outside of our container (but mount).

**Comment by gloubsi** [comment]
I would like to ask you if we have to remove .nf-test folder with each nft-bam release update ? It seems so with this observation  that nft-bam doesn't overwrite the older plugin version with the newest version in .nf-test folder.

**Comment by nvnieuwk** [comment]
I personally have no issues with upgrading the plugin, but the nf-test devs are aware that the system currently is pretty minimalistic (hence why I tagged @lukfor here so he could see it :))

**Comment by nvnieuwk** [comment]
But this seems more like an nf-test issue rather than an nft-bam issue

**Comment by gloubsi** [comment]
Ok. Thank you again for your help. I’m closing this issue.
