### ISSUE TITLE
"dev" docs are misleading

### ISSUE THREAD

**Issue by edmundmiller** [nvnieuwk/nft-bam#5]
They have 

```
config {
    plugins {
        load "nft-bam@0.1.1"
    }
}
```

Which is not the latest version 🫠

**Comment by nvnieuwk** [comment]
Hmmm that's strange. It should update automatically. I'll take a look, thank you for reporting!

**Comment by nvnieuwk** [comment]
I forgot to bump the version back to dev. The docs should now be up to date :)
